<template><div><h1 id="python" tabindex="-1"><a class="header-anchor" href="#python" aria-hidden="true">#</a> Python</h1>
<p>pragmatic</p>
<p>immediate</p>
<p>approximate</p>
<p>backport</p>
<p>circumstance</p>
<p>coercion</p>
<p>compound</p>
<p>contiguous</p>
<p>decoupling</p>
<p>deliberately</p>
<p>dispatch</p>
<p>encapsulation</p>
<p>generic function</p>
<p>granularity</p>
<p>gratuitously</p>
<p>heterogeneous</p>
<p>hierarchies</p>
<p>homogeneous</p>
<p>inheritance</p>
<p>introspection</p>
<p>polymorphism</p>
<p>precedence</p>
<p>provisional</p>
<p>robust</p>
<p>short-circuit</p>
<p>wildcard</p>
<p>open-circuit</p>
<p>contingency</p>
<p>feedback</p>
<p>sinusoidal</p>
</div></template>
