<template><div><h1 id="swift" tabindex="-1"><a class="header-anchor" href="#swift" aria-hidden="true">#</a> Swift</h1>
<p>pragmatic</p>
<p>immediate</p>
<p>precedence</p>
<p>infix</p>
<p>prefix</p>
<p>postfix</p>
<p>unary</p>
<p>overflow</p>
<p>guard</p>
<p>bitwise</p>
<p>extension</p>
<p>protocol</p>
<p>internal</p>
<p>clause</p>
<p>annotation</p>
<p>constraint</p>
<p>optional</p>
<p>closures</p>
</div></template>
